apaWebsite:
  loginLink: https://accounts.poolplayers.com/login
  baseLink: https://league.poolplayers.com
  chicagoCentralLink: https://league.poolplayers.com/centralchicago
  sessionBaseLink: https://league.poolplayers.com/centralchicago/divisions/session/
  teamBaseLink: https://league.poolplayers.com/centralchicago/team/
  teamMatchBaseLink: https://league.poolplayers.com/centralchicago/match/
  divisionBaseLink: https://league.poolplayers.com/centralchicago/divisions/
waitTimes:
  implicitWaitTime: 10
  sleepTime: 3

# 8-ball, 9-ball, or masters
format: 8-ball
debugMode: true
typecheck: false

predictionAccuracy:
  # When calculating expected points, if two skill level types have over 326 games between them, use the average of all their points scored
  # If 326 games or less are played between the two skill level types, use medians
  expectedPtsMethod: average