apaWebsite:
  loginLink: https://accounts.poolplayers.com/login
  dashboardLink: https://league.poolplayers.com/dashboard
  # Should follow format https://league.poolplayers.com/<region>/disions/<leagueId>/standings
  # https://league.poolplayers.com/centralchicago/divisions/366534/standings/
  # Fall 2023 Tuesday: https://league.poolplayers.com/centralchicago/divisions/373316
  # Fall 2023 Monday: https://league.poolplayers.com/centralchicago/divisions/373319
  # Fall 2023 Thursday: https://league.poolplayers.com/centralchicago/divisions/373318
  # Spring 2024 Monday: https://league.poolplayers.com/centralchicago/divisions/379653
  # Spring 2024 Thursday: https://league.poolplayers.com/centralchicago/divisions/379652
  # Summer 2024 Thursday: https://league.poolplayers.com/centralchicago/divisions/387820
  divisionLink: https://league.poolplayers.com/centralchicago/divisions/379653
  baseLink: https://league.poolplayers.com
  sessionBaseLink: https://league.poolplayers.com/centralchicago/divisions/session/
  teamBaseLink: https://league.poolplayers.com/centralchicago/team/
  teamMatchBaseLink: https://league.poolplayers.com/centralchicago/match/
  divisionBaseLink: https://league.poolplayers.com/centralchicago/divisions/
  startingSession: 78
  currentSession: 132
waitTimes:
  implicitWaitTime: 10
  sleepTime: 3
playerInQuestion: Quinn Baker
teamInQuestion: Miniclip
# VVVVVV  MUST BE IN ALL CAPS  VVVVVV
sessionSeasonInQuestion: SPRING
sessionYearInQuestion: 2024

# 8-ball, 9-ball, or masters
format: 8-ball
debugMode: true
refreshTeams: false
myInfo:
  memberId: 60903003
  teamIds: [12531019, 12536150]

predictionAccuracy:
  # When calculating expected points, if two skill level types have over 326 games between them, use the average of all their points scored
  # If 326 games or less are played between the two skill level types, use medians
  expectedPtsMethod: average