apa_website:
  login_link: https://accounts.poolplayers.com/login
  dashboard_link: https://league.poolplayers.com/dashboard
  # Should follow format https://league.poolplayers.com/<region>/disions/<leagueId>/standings
  division_link: # DIVISION_LINK_HERE
wait_times:
  implicit_wait_time: 10
  sleep_time: 3
player_in_question: # PLAYER_NAME_HERE
team_in_question: # TEAM_NAME_HERE



















apa_credentials:
  email: # YOUR_EMAIL_HERE
  password: # YOUR_PASSWORD_HERE